package com.gitup.app.data.model

import com.google.gson.JsonObject
import com.google.gson.annotations.SerializedName

// Dynamic manifest structure
data class ManifestData(
    val version: String? = null,
    @SerializedName("last_updated")
    val lastUpdated: String? = null,
    @SerializedName("base_url")
    val baseUrl: String? = null,
    val categories: Map<String, List<JsonObject>> = emptyMap()
)

// Parsed manifest info
data class ManifestInfo(
    val filePath: String,
    val sha: String,
    val categories: List<String>,
    val sampleFields: Map<String, Any>,
    val baseUrl: String?
)

// Form field definition
data class FormField(
    val key: String,
    val label: String,
    val type: FieldType,
    val required: Boolean = true,
    val autoGenerated: Boolean = false,
    val options: List<String>? = null
)

enum class FieldType {
    TEXT,
    DROPDOWN,
    BOOLEAN,
    NUMBER,
    AUTO_GENERATED
}

// Upload with manifest data
data class FileUploadWithManifest(
    val fileName: String,
    val fileBytes: ByteArray,
    val uploadPath: String,
    val manifestData: Map<String, Any>
)
