package com.gitup.app.data.repository

import com.gitup.app.data.model.FormField
import com.gitup.app.data.model.FieldType
import com.gitup.app.data.model.ManifestInfo
import com.google.gson.Gson
import com.google.gson.JsonObject
import com.google.gson.JsonParser
import java.text.SimpleDateFormat
import java.util.*

class ManifestRepository {
    
    private val gson = Gson()
    
    fun parseManifest(content: String): ManifestInfo? {
        return try {
            val jsonObject = JsonParser.parseString(content).asJsonObject
            
            // Extract categories (any array field except metadata)
            val categories = mutableListOf<String>()
            val metadataKeys = setOf("version", "last_updated", "base_url")
            
            jsonObject.keySet().forEach { key ->
                if (!metadataKeys.contains(key) && jsonObject.get(key).isJsonArray) {
                    categories.add(key)
                }
            }
            
            // Get sample fields from first item of first category
            val sampleFields = mutableMapOf<String, Any>()
            if (categories.isNotEmpty()) {
                val firstCategory = categories[0]
                val items = jsonObject.getAsJsonArray(firstCategory)
                if (items.size() > 0) {
                    val firstItem = items[0].asJsonObject
                    firstItem.keySet().forEach { key ->
                        val value = firstItem.get(key)
                        when {
                            value.isJsonPrimitive -> {
                                val primitive = value.asJsonPrimitive
                                sampleFields[key] = when {
                                    primitive.isBoolean -> primitive.asBoolean
                                    primitive.isNumber -> primitive.asNumber
                                    else -> primitive.asString
                                }
                            }
                        }
                    }
                }
            }
            
            val baseUrl = if (jsonObject.has("base_url")) {
                jsonObject.get("base_url").asString
            } else null
            
            ManifestInfo(
                filePath = "manifest.json",
                sha = "",
                categories = categories,
                sampleFields = sampleFields,
                baseUrl = baseUrl
            )
        } catch (e: Exception) {
            null
        }
    }
    
    fun generateFormFields(manifestInfo: ManifestInfo): List<FormField> {
        val fields = mutableListOf<FormField>()
        
        // Category dropdown
        fields.add(
            FormField(
                key = "category",
                label = "Category",
                type = FieldType.DROPDOWN,
                required = true,
                options = manifestInfo.categories
            )
        )
        
        // Generate fields based on sample
        manifestInfo.sampleFields.forEach { (key, value) ->
            when {
                key == "id" -> {
                    fields.add(
                        FormField(
                            key = key,
                            label = "ID",
                            type = FieldType.AUTO_GENERATED,
                            autoGenerated = true
                        )
                    )
                }
                key == "display_name" || key == "name" -> {
                    fields.add(
                        FormField(
                            key = key,
                            label = "Display Name",
                            type = FieldType.TEXT,
                            required = true
                        )
                    )
                }
                key == "category" -> {
                    // Already added as dropdown
                }
                key.contains("free") || key.contains("premium") || value is Boolean -> {
                    fields.add(
                        FormField(
                            key = key,
                            label = formatLabel(key),
                            type = FieldType.BOOLEAN,
                            required = false
                        )
                    )
                }
                key.contains("size") || key.contains("bytes") -> {
                    fields.add(
                        FormField(
                            key = key,
                            label = formatLabel(key),
                            type = FieldType.AUTO_GENERATED,
                            autoGenerated = true
                        )
                    )
                }
                key.contains("url") || key.contains("path") -> {
                    fields.add(
                        FormField(
                            key = key,
                            label = formatLabel(key),
                            type = FieldType.AUTO_GENERATED,
                            autoGenerated = true
                        )
                    )
                }
                else -> {
                    // Other text fields
                    if (!key.contains("file_name")) {
                        fields.add(
                            FormField(
                                key = key,
                                label = formatLabel(key),
                                type = FieldType.TEXT,
                                required = false
                            )
                        )
                    }
                }
            }
        }
        
        return fields
    }
    
    fun generateManifestEntry(
        formData: Map<String, Any>,
        fileName: String,
        filePath: String,
        fileSize: Long,
        baseUrl: String?,
        manifestInfo: ManifestInfo
    ): JsonObject {
        val entry = JsonObject()
        
        val category = formData["category"] as? String ?: "default"
        val displayName = (formData["display_name"] as? String ?: fileName.substringBeforeLast(".")).trim()
        
        // Generate ID
        val id = generateId(category, displayName)
        entry.addProperty("id", id)
        
        // Add all form fields
        manifestInfo.sampleFields.keys.forEach { key ->
            when (key) {
                "id" -> entry.addProperty(key, id)
                "display_name", "name" -> entry.addProperty(key, displayName)
                "category" -> entry.addProperty(key, category.capitalize())
                "file_name" -> entry.addProperty(key, fileName)
                "file_path" -> entry.addProperty(key, filePath)
                "size_bytes" -> entry.addProperty(key, fileSize)
                "size_display" -> entry.addProperty(key, formatFileSize(fileSize))
                "preview_url" -> {
                    val url = if (baseUrl != null) "$baseUrl/$filePath" else filePath
                    entry.addProperty(key, url)
                }
                "download_url" -> {
                    val url = if (baseUrl != null) "$baseUrl/$filePath" else filePath
                    entry.addProperty(key, url)
                }
                else -> {
                    // Use form data or default
                    val value = formData[key]
                    when (value) {
                        is Boolean -> entry.addProperty(key, value)
                        is Number -> entry.addProperty(key, value)
                        is String -> entry.addProperty(key, value)
                        else -> {
                            // Use default from sample
                            val sampleValue = manifestInfo.sampleFields[key]
                            when (sampleValue) {
                                is Boolean -> entry.addProperty(key, sampleValue)
                                is Number -> entry.addProperty(key, sampleValue)
                                else -> entry.addProperty(key, sampleValue?.toString() ?: "")
                            }
                        }
                    }
                }
            }
        }
        
        return entry
    }
    
    fun updateManifest(
        currentContent: String,
        newEntry: JsonObject,
        category: String
    ): String {
        val jsonObject = JsonParser.parseString(currentContent).asJsonObject
        
        // Update last_updated
        val dateFormat = SimpleDateFormat("yyyy-MM-dd", Locale.US)
        jsonObject.addProperty("last_updated", dateFormat.format(Date()))
        
        // Add entry to category
        val categoryArray = if (jsonObject.has(category)) {
            jsonObject.getAsJsonArray(category)
        } else {
            jsonObject.add(category, com.google.gson.JsonArray())
            jsonObject.getAsJsonArray(category)
        }
        
        categoryArray.add(newEntry)
        
        return gson.toJson(jsonObject)
    }
    
    private fun generateId(category: String, displayName: String): String {
        val categoryPrefix = category.lowercase().replace(" ", "_")
        val namePart = displayName.trim().lowercase()
            .replace(" ", "_")
            .replace(Regex("[^a-z0-9_]"), "")
            .replace(Regex("_+"), "_")
            .trim('_')
        return "${categoryPrefix}_${namePart}"
    }
    
    private fun formatFileSize(bytes: Long): String {
        return when {
            bytes < 1024 -> "$bytes B"
            bytes < 1024 * 1024 -> "${bytes / 1024} KB"
            bytes < 1024 * 1024 * 1024 -> String.format("%.1f MB", bytes / (1024.0 * 1024.0))
            else -> String.format("%.2f GB", bytes / (1024.0 * 1024.0 * 1024.0))
        }
    }
    
    private fun formatLabel(key: String): String {
        return key.split("_")
            .joinToString(" ") { it.capitalize() }
    }
    
    private fun String.capitalize(): String {
        return this.replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() }
    }
}
